### ISSUE TITLE
Won't work with Ionic 4 

### ISSUE THREAD

**Issue by abhiking-agrawal** [walterchau/ionic-mqtt#1]
Getting Below error:

ERROR in ./node_modules/ionic-mqtt/dist/mqtt.module.js
Module not found: Error: Can't resolve 'ionic-angular' in 'C:\WorkStation\VisionApp\node_modules\ionic-mqtt\dist'

Here is my Ionic Info:
   Ionic CLI                     : 5.2.1 (C:\Users\Skyhook\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0
Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Plugins   : not available

**Comment by 0x-KChau** [comment]
Thanks for your error report. The package was built for ionic 3 previously, but now migrated to ionic 4 successfully. Please download the latest version of package, which is ionic-mqtt@1.1.5, and the error above should be solved.
