### ISSUE TITLE
Is possible to do a connection with ssl to the mqtt server?

### ISSUE THREAD

**Issue by dherediat97** [walterchau/ionic-mqtt#4]
Hello @ketherchau and @walterchau , first of all good job 👍 

In my case the mqtt is in ssl(aka wss)so, i need if it is possible, that your plugin admit that.

I tried put that(wss://anotherbroker.com) but don't work.

And also put a simple authentication, like user and password. Because i also need that.

Only more to add and again goodjob! 🥇 

Greetings @dherediat97

**Comment by anhtumai** [comment]
I am wondering is it possible to do it with Paho MQTT as well

**Comment by dherediat97** [comment]
I think that yes because in them code have this:
[https://github.com/eclipse/paho.mqtt.javascript/blob/master/src/paho-mqtt.js#L1939](https://github.com/eclipse/paho.mqtt.javascript/blob/master/src/paho-mqtt.js#L1939).

I see this issue [https://github.com/eclipse/paho.mqtt.javascript/issues/88](https://github.com/eclipse/paho.mqtt.javascript/issues/88), so they fixed this.


Is right if the team of this plugin develop in the time of the paho client of eclipse, havent that parameter so dont worry 👍 .

[https://github.com/eclipse/paho.mqtt.javascript/issues/88#issuecomment-291202604](https://github.com/eclipse/paho.mqtt.javascript/issues/88#issuecomment-291202604)

Greetings @dherediat97

**Comment by anhtumai** [comment]
In my case, I want to use Ionic to dev a mobile app. SSL feature in paho-mqtt js utilized the browser security, so that, it will fail when running on Android. According to the comment, there is no way to use certificates at the moment.

**Comment by dherediat97** [comment]
So use this [https://github.com/sclausen/ngx-mqtt](https://github.com/sclausen/ngx-mqtt), i use and can connect with the mqtt server

**Comment by anhtumai** [comment]
I use paho-mqtt and it works fine as well. The only problem is that I want to enable wss-web socket secured, and use key, pem file for security. I am waiting for ionic to support that feature. This is the link to my project: https://github.com/anhtumai/AccelerometerAppWithMQTT

**Comment by dherediat97** [comment]
Ok @anhtumai , yes, i think that another repository of mqtt in js in github will work with certificate(key, pem, or whatever) for mqtt but ofc, if this or other support this feature is a good notice, i dont need the certificate only have the protocol with 'wss' so i use other and work, but yet i see more easy and more clean this plugin that the other. 👍
